/* ==========================================================================
   virgule. — les photos
   --------------------------------------------------------------------------
   Pour ajouter une photo, ajoute un objet à la liste :

   {
     image: "photos/ma-photo.jpg",   // chemin vers ton fichier (ou URL)
     alt: "description pour les lecteurs d'écran",
     titre: "le titre de la photo",
     categorie: "paysages",          // paysages | macro | animaux | portraits
                                     // architecture | détails | lumière
     date: "mai 2025",
     lieu: "Vercors",
     description: "petit texte affiché en grand format.",
     phrase: "la petite phrase absurde au survol.",
     taille: "grande",               // grande | panorama | haute | moyenne | petite
     ratio: "3/2",                   // facultatif — les VRAIES proportions du fichier
     favori: true,                   // facultatif — la montre aussi sur l'accueil
     evenement: "Camille & Jonas",   // facultatif — la prestation d'où vient la photo
   }

   `evenement` doit être écrit EXACTEMENT pareil sur toutes les photos d'une même
   prestation : c'est ce texte qui devient un bouton dans la barre de filtres de
   photos.html, sous « par événement ». Le site en fabrique aussi une forme
   d'adresse — minuscules, sans accents, espaces en tirets : « Camille & Jonas »
   devient « camille-jonas ». C'est cette forme que les billets du palmarès, sur
   l'accueil, mettent dans leur lien : photos.html?evenement=camille-jonas.
   Si tu ajoutes un billet là-bas, vérifie que le lien tombe sur la bonne forme.

   Toutes les photos apparaissent sur photos.html, triables par catégorie
   (la barre de boutons se fabrique toute seule depuis les catégories
   présentes ici). L'accueil, lui, ne montre que celles marquées
   `favori: true`. Si aucune n'est marquée, il prend les six premières,
   pour qu'il n'y ait jamais de page vide.

   Les deux pages rangent les photos en colonnes : toutes prennent la largeur
   de leur colonne, et c'est leur forme qui fait la différence de hauteur.
   `taille` ne commande donc pas de largeur — elle sert à deviner les
   proportions quand `ratio` n'est pas renseigné, et à choisir le bon fichier
   selon l'écran. Dès que tu mets `ratio`, c'est lui qui décide de la forme.
   Une photo n'est jamais déformée ni recadrée : elle garde ses proportions
   dans tous les cas.

   Astuce vitesse : si le chemin contient `{w}`, le site choisit tout seul
   la bonne taille parmi 700, 1100 et 1600 px de large.

   --------------------------------------------------------------------------
   Les fichiers de photos/site/ ont été fabriqués depuis tes originaux (dossier
   photos/), en trois largeurs webp chacun. Les originaux sont restés en place :
   ne les supprime pas, c'est à partir d'eux qu'on regénérera si besoin.

   Deux champs sont volontairement laissés vides, parce que je n'avais pas de
   quoi les remplir honnêtement :
     · `lieu` — tes fichiers n'ont pas de coordonnées GPS. À toi de les écrire,
       c'est deux clics au crayon depuis le mode édition.
     · `evenement` — je ne sais pas lesquelles viennent d'une prestation. Une
       fois renseigné, la photo apparaît dans le filtre « par événement » et
       dans le billet correspondant du palmarès.
   Les `date` viennent des données EXIF de tes fichiers : elles sont exactes.
   Les titres et les petites phrases sont de moi — change ce qui ne te
   ressemble pas, c'est ta voix qui doit parler.
   ========================================================================== */

const PHOTOS = [
  {
    image: "photos/site/arbre-champ-{w}.webp",
    alt: "un arbre isolé au milieu d'un champ doré, montagnes bleues au fond",
    titre: "l'arbre n'attendait personne",
    categorie: "paysages",
    date: "juillet 2025",
    lieu: "",
    description: "il occupait le champ tout seul depuis un moment. j'ai juste eu la politesse de m'arrêter.",
    phrase: "il n'a pas bougé de la séance.",
    taille: "panorama",
    ratio: "3/2",
    favori: true,
  },
  {
    image: "photos/site/escalier-vert-{w}.webp",
    alt: "un escalier de pierre grimpe entre deux murs de végétation dense",
    titre: "l'escalier montait quelque part",
    categorie: "architecture",
    date: "juillet 2025",
    lieu: "",
    description: "je n'ai pas vérifié où. la photo était en bas, c'était déjà bien.",
    phrase: "je n'ai pas monté les marches.",
    taille: "haute",
    ratio: "2/3",
    favori: true,
  },
  {
    image: "photos/site/bourdon-lavande-{w}.webp",
    alt: "un bourdon posé sur un épi de lavande, en très gros plan",
    titre: "le bourdon travaillait",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "il n'a jamais levé la tête. c'est un professionnel, contrairement à moi.",
    phrase: "lui au moins savait ce qu'il faisait.",
    taille: "moyenne",
    ratio: "3/2",
    favori: true,
  },
  {
    image: "photos/site/chien-roux-{w}.webp",
    alt: "un chien roux, langue sortie, regarde l'objectif en pleine lumière",
    titre: "le chien approuvait",
    categorie: "animaux",
    date: "juillet 2025",
    lieu: "",
    description: "il a tenu la pose exactement le temps qu'il fallait, puis il est parti sans un mot.",
    phrase: "il a compris avant moi.",
    taille: "grande",
    ratio: "3/2",
    favori: true,
  },
  {
    image: "photos/site/soleil-crete-{w}.webp",
    alt: "le soleil disparaît derrière une crête de montagne, ciel orange et nuages sombres",
    titre: "le soleil s'en allait par la crête",
    categorie: "lumière",
    date: "août 2026",
    lieu: "",
    description: "trois minutes de ça, et puis plus rien. c'est exactement pour ça que je me lève.",
    phrase: "trois minutes, montre en main.",
    taille: "panorama",
    ratio: "3/2",
    favori: true,
  },
  {
    image: "photos/site/pont-du-gard-{w}.webp",
    alt: "le Pont du Gard vu depuis un chemin bordé d'arbres, ciel nuageux",
    titre: "deux mille ans, toujours debout",
    categorie: "architecture",
    date: "octobre 2025",
    lieu: "Pont du Gard",
    description: "il tient depuis vingt siècles. mon trépied a tenu quatre minutes.",
    phrase: "personne ne l'a aidé.",
    taille: "grande",
    ratio: "3/2",
  },
  {
    image: "photos/site/eclipse-{w}.webp",
    alt: "un croissant de soleil éclipsé, seul dans un ciel entièrement noir",
    titre: "le soleil, en moins bien",
    categorie: "lumière",
    date: "août 2026",
    lieu: "",
    description: "une éclipse, ça ne prévient qu'une fois. j'étais prêt, pour une fois.",
    phrase: "il est revenu, rassure-toi.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/coucher-gris-{w}.webp",
    alt: "un coucher de soleil gris-bleu, une bande orange court sur les collines",
    titre: "la seule bande de lumière du soir",
    categorie: "lumière",
    date: "août 2026",
    lieu: "",
    description: "tout le reste du ciel avait renoncé. celle-là s'est accrochée deux minutes de plus.",
    phrase: "le reste du ciel n'a rien fait.",
    taille: "panorama",
    ratio: "3/2",
  },
  {
    image: "photos/site/bandes-rouges-{w}.webp",
    alt: "des nuages sombres striés de rouge au-dessus de collines, au couchant",
    titre: "les nuages faisaient les intéressants",
    categorie: "lumière",
    date: "août 2026",
    lieu: "",
    description: "ils se sont mis en rang tout seuls. je n'ai vraiment rien demandé.",
    phrase: "aucune retouche. tout le mérite est à eux.",
    taille: "panorama",
    ratio: "3/2",
  },
  {
    image: "photos/site/paon-du-jour-{w}.webp",
    alt: "un papillon paon-du-jour posé sur un brin de lavande, feuillage vert sombre derrière",
    titre: "quatre yeux qui n'en sont pas",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "il porte des yeux sur les ailes pour faire peur. ça marche très bien sur moi.",
    phrase: "il m'a regardé avec ses ailes.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/pieride-lavande-{w}.webp",
    alt: "un papillon blanc sur un épi de lavande, contre-jour doux",
    titre: "blanc sur violet",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "il s'est posé pile où il fallait. c'est la seule fois de la journée.",
    phrase: "la seule prise réussie sur trente.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/bourdon-ronce-{w}.webp",
    alt: "un bourdon sur une fleur de ronce rose, fond vert très sombre",
    titre: "la ronce avait de la visite",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "il faisait presque nuit sous les feuilles. lui, ça ne le dérangeait pas.",
    phrase: "j'ai eu plus peur que lui.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/papillon-lichen-{w}.webp",
    alt: "un papillon aux ailes marbrées posé sur une branche couverte de lichen jaune",
    titre: "camouflage moyennement réussi",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "il se croyait invisible sur son lichen. il avait tort, mais de peu.",
    phrase: "je l'ai vu. il ne le sait pas.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/hemerocalle-{w}.webp",
    alt: "une hémérocalle orange grande ouverte, pétales éclatants sur fond vert flou",
    titre: "une fleur qui ne dure qu'un jour",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "l'hémérocalle s'ouvre le matin et referme le soir, définitivement. il fallait passer ce jour-là.",
    phrase: "le lendemain, plus rien.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/laurier-ciel-{w}.webp",
    alt: "une fleur de laurier-rose blanche se détache sur un ciel bleu profond",
    titre: "blanc contre bleu, sans discussion",
    categorie: "détails",
    date: "août 2025",
    lieu: "",
    description: "deux couleurs, rien d'autre dans le cadre. les photos les plus simples sont les plus longues à trouver.",
    phrase: "j'ai tourné dix minutes autour.",
    taille: "haute",
    ratio: "2/3",
  },
  {
    image: "photos/site/coq-noir-{w}.webp",
    alt: "un coq noir aux plumes irisées, dressé de profil sur un chemin de terre",
    titre: "monsieur ne se déplace pas pour rien",
    categorie: "animaux",
    date: "juillet 2025",
    lieu: "",
    description: "il m'a laissé trois secondes, de profil, et il a jugé que ça suffirait. il avait raison.",
    phrase: "c'est lui qui a choisi l'angle.",
    taille: "haute",
    ratio: "2/3",
  },
  {
    image: "photos/site/chien-pierre-{w}.webp",
    alt: "un chien roux allongé sur un rocher, forêt sombre en arrière-plan",
    titre: "le chien tenait le poste",
    categorie: "animaux",
    date: "juillet 2025",
    lieu: "",
    description: "il surveillait quelque chose, quelque part. il ne m'a pas dit quoi.",
    phrase: "il surveillait. je n'ai pas demandé quoi.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/moineau-{w}.webp",
    alt: "un moineau posé sur une branche fine, feuillage clair autour",
    titre: "le moineau avait un avis",
    categorie: "animaux",
    date: "juillet 2025",
    lieu: "",
    description: "il l'a donné pendant une bonne minute, sans s'interrompre. je n'ai pas tout compris.",
    phrase: "il criait. j'ai photographié.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/oiseau-poteau-{w}.webp",
    alt: "en noir et blanc, un oiseau perché au sommet d'un poteau de béton, ciel uni",
    titre: "un oiseau, un poteau, rien d'autre",
    categorie: "détails",
    date: "août 2025",
    lieu: "",
    description: "le ciel était parfaitement vide ce jour-là. c'est plus rare qu'on ne croit.",
    phrase: "le ciel a bien voulu se taire.",
    taille: "haute",
    ratio: "2/3",
    favori: true,
  },
  {
    image: "photos/site/croix-ville-{w}.webp",
    alt: "une grande croix de bois domine une ville étalée dans la vallée, ciel bleu et nuages",
    titre: "la croix regardait la ville",
    categorie: "paysages",
    date: "juillet 2025",
    lieu: "",
    description: "elle est plantée là depuis longtemps et elle a la meilleure vue de la commune.",
    phrase: "elle avait la meilleure place.",
    taille: "grande",
    ratio: "3/2",
  },
  {
    image: "photos/site/ville-perchee-{w}.webp",
    alt: "une ville ancienne perchée sur un plateau rocheux, cathédrale gothique au sommet",
    titre: "la ville avait pris de la hauteur",
    categorie: "architecture",
    date: "juillet 2025",
    lieu: "",
    description: "construire tout ça là-haut était une très mauvaise idée, et c'est exactement pour ça que c'est beau.",
    phrase: "personne n'a demandé pourquoi si haut.",
    taille: "grande",
    ratio: "3/2",
  },
  {
    image: "photos/site/ville-falaise-{w}.webp",
    alt: "des maisons de pierre s'accrochent au bord d'une falaise, cathédrale au-dessus",
    titre: "les maisons tenaient bon",
    categorie: "architecture",
    date: "juillet 2025",
    lieu: "",
    description: "elles sont posées au bord depuis des siècles et personne n'a l'air inquiet.",
    phrase: "je n'aurais pas dormi là.",
    taille: "grande",
    ratio: "3/2",
  },
  {
    image: "photos/site/eglise-lac-{w}.webp",
    alt: "une église au bord d'un plan d'eau, village accroché à la colline derrière",
    titre: "l'église avait les pieds dans l'eau",
    categorie: "architecture",
    date: "juillet 2025",
    lieu: "",
    description: "elle se reflétait mieux qu'elle ne posait. je l'ai photographiée deux fois du coup.",
    phrase: "le reflet était plus coopératif.",
    taille: "haute",
    ratio: "2/3",
  },
  {
    image: "photos/site/croix-vallee-{w}.webp",
    alt: "une croix de bois se détache sur un ciel bleu, la vallée et la ville en contrebas",
    titre: "la croix, la ville, et beaucoup de ciel",
    categorie: "paysages",
    date: "juillet 2025",
    lieu: "",
    description: "les nuages ont mis vingt minutes à se placer correctement. j'ai attendu.",
    phrase: "les nuages ont pris leur temps.",
    taille: "grande",
    ratio: "3/2",
  },
  {
    image: "photos/site/croix-contrejour-{w}.webp",
    alt: "la même croix vue de plus loin, la ville étalée sous un grand ciel nuageux",
    titre: "un pas en arrière",
    categorie: "paysages",
    date: "juillet 2025",
    lieu: "",
    description: "même endroit, trois mètres plus loin. parfois c'est tout ce qui manque.",
    phrase: "trois mètres de différence.",
    taille: "grande",
    ratio: "3/2",
  },
  {
    image: "photos/site/ville-contraste-{w}.webp",
    alt: "en noir et blanc très contrasté, une ville perchée encadrée par des feuillages sombres",
    titre: "la ville, en noir et blanc franc",
    categorie: "architecture",
    date: "juillet 2025",
    lieu: "",
    description: "pas de demi-teintes ce jour-là. le feuillage a fait le cadre tout seul.",
    phrase: "il n'y avait pas de gris.",
    taille: "grande",
    ratio: "3/2",
  },
  {
    image: "photos/site/ronce-barbeles-{w}.webp",
    alt: "des fleurs de ronce roses poussent le long d'un fil de fer barbelé",
    titre: "la ronce et le barbelé",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "deux façons de dire « n'approchez pas ». une seule est jolie.",
    phrase: "les deux piquent, mais pas pareil.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/papillon-lichen-2-{w}.webp",
    alt: "un papillon aux ailes marbrées sur une branche de lichen, vu de plus loin",
    titre: "la branche entière, cette fois",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "j'ai reculé pour montrer le lichen. il est aussi beau que le papillon.",
    phrase: "le lichen méritait sa photo.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/pieride-lavande-2-{w}.webp",
    alt: "un papillon blanc butine un épi de lavande, ailes fermées",
    titre: "il n'a pas ouvert les ailes",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "j'ai attendu qu'il les ouvre pendant un quart d'heure. il est parti fermé.",
    phrase: "quinze minutes pour rien.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/hesperie-lavande-{w}.webp",
    alt: "un petit papillon orange posé au sommet d'un épi de lavande",
    titre: "le plus petit de la lavande",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "il fait deux centimètres et il ne tient jamais en place. celui-là a fait une exception.",
    phrase: "deux centimètres de patience.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/nacre-herbe-{w}.webp",
    alt: "un papillon nacré orange tacheté, posé dans l'herbe sèche",
    titre: "orange sur paille",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "il s'était posé sur exactement la même couleur que lui. mauvais calcul.",
    phrase: "il se croyait discret.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/nacre-pierre-{w}.webp",
    alt: "un papillon nacré ailes ouvertes sur une dalle de pierre claire",
    titre: "ailes ouvertes, enfin",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "après une demi-heure à courir après des papillons fermés, celui-là s'est ouvert tout seul.",
    phrase: "celui-là, je l'ai mérité.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/punaise-tige-{w}.webp",
    alt: "une punaise rouge et noire remonte une tige velue",
    titre: "la punaise faisait l'ascension",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "elle montait depuis un moment, très concentrée. je n'ai pas voulu la déranger.",
    phrase: "elle n'est jamais redescendue.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/hemerocalles-{w}.webp",
    alt: "deux hémérocalles orange grandes ouvertes parmi les feuillages",
    titre: "deux d'un coup",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "",
    description: "elles ne durent qu'un jour chacune, et elles avaient choisi le même.",
    phrase: "elles s'étaient donné le mot.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/canna-rouge-{w}.webp",
    alt: "une fleur de canna rouge vif se détache d'un massif de feuilles sombres",
    titre: "la seule rouge du massif",
    categorie: "détails",
    date: "juillet 2025",
    lieu: "",
    description: "tout le reste était vert. elle avait décidé de ne pas suivre.",
    phrase: "elle n'a demandé l'avis de personne.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/fleurs-jaunes-{w}.webp",
    alt: "un bouquet de petites fleurs jaunes au milieu des herbes sèches",
    titre: "du jaune dans le sec",
    categorie: "détails",
    date: "juillet 2025",
    lieu: "",
    description: "il n'avait pas plu depuis longtemps. elles n'avaient pas l'air au courant.",
    phrase: "personne ne les avait prévenues.",
    taille: "moyenne",
    ratio: "3/2",
  },
  {
    image: "photos/site/laurier-feuilles-{w}.webp",
    alt: "une fleur de laurier-rose entourée de longues feuilles étroites",
    titre: "rose entre les lames",
    categorie: "détails",
    date: "août 2025",
    lieu: "",
    description: "les feuilles font des barreaux. la fleur passe quand même.",
    phrase: "elle est passée entre les barreaux.",
    taille: "haute",
    ratio: "2/3",
  },
  {
    image: "photos/site/laurier-rose-ciel-{w}.webp",
    alt: "une fleur de laurier-rose se découpe sur un ciel bleu intense",
    titre: "rose contre bleu",
    categorie: "détails",
    date: "août 2025",
    lieu: "",
    description: "le ciel était de cette couleur-là toute la journée. j'en ai profité.",
    phrase: "le ciel n'a pas bougé de la journée.",
    taille: "haute",
    ratio: "2/3",
  },
  {
    image: "photos/site/lauriers-ciel-{w}.webp",
    alt: "plusieurs fleurs de laurier-rose dressées vers un ciel bleu uni",
    titre: "tout le buisson regardait en l'air",
    categorie: "détails",
    date: "août 2025",
    lieu: "",
    description: "elles poussent toutes vers le haut, sans se concerter. ça donne ça.",
    phrase: "elles regardaient toutes dans le même sens.",
    taille: "haute",
    ratio: "2/3",
  },
  {
    image: "photos/site/chat-muret-{w}.webp",
    alt: "un chat roux et blanc assis sur un muret, arbres flous derrière",
    titre: "le chat tolérait ma présence",
    categorie: "animaux",
    date: "juillet 2025",
    lieu: "",
    description: "il m'a laissé approcher jusqu'à une distance précise, puis il a arrêté de me laisser faire.",
    phrase: "un mètre de plus et c'était fini.",
    taille: "haute",
    ratio: "2/3",
  },
  {
    image: "photos/site/coucher-nuages-{w}.webp",
    alt: "le soleil derrière un banc de nuages sombres, ciel orange au-dessus des collines",
    titre: "le soleil derrière le rideau",
    categorie: "lumière",
    date: "août 2026",
    lieu: "",
    description: "il est resté caché tout le temps. ça ne l'a pas empêché d'éclairer tout le reste.",
    phrase: "on ne le voit pas. il est là.",
    taille: "panorama",
    ratio: "3/2",
  },
  {
    image: "photos/site/coucher-bandes-{w}.webp",
    alt: "des bandes de nuages rouges et sombres empilées au-dessus d'une ligne de collines",
    titre: "le ciel s'était mis en couches",
    categorie: "lumière",
    date: "août 2026",
    lieu: "",
    description: "cinq bandes bien nettes, l'une sur l'autre. ça n'a tenu que quelques minutes.",
    phrase: "cinq couches, comptées.",
    taille: "panorama",
    ratio: "3/2",
  },
  {
    image: "photos/site/eclipse-1-{w}.webp",
    alt: "le soleil très légèrement entamé par la lune, dans un ciel noir",
    titre: "l'éclipse, tout début",
    categorie: "lumière",
    date: "août 2026",
    lieu: "",
    description: "à peine une encoche sur le bord. si on ne sait pas, on ne voit rien.",
    phrase: "ça commence par presque rien.",
    taille: "haute",
    ratio: "2/3",
  },
  {
    image: "photos/site/eclipse-2-{w}.webp",
    alt: "le croissant solaire se creuse, la lune mord un tiers du disque",
    titre: "l'éclipse, un tiers",
    categorie: "lumière",
    date: "août 2026",
    lieu: "",
    description: "à ce stade la lumière change déjà autour, sans qu'on sache dire pourquoi.",
    phrase: "la lumière était devenue bizarre.",
    taille: "haute",
    ratio: "2/3",
  },
  {
    image: "photos/site/eclipse-3-{w}.webp",
    alt: "le soleil réduit à un croissant épais dans un ciel entièrement noir",
    titre: "l'éclipse, la moitié",
    categorie: "lumière",
    date: "août 2026",
    lieu: "",
    description: "la moitié du soleil en moins et il fait encore grand jour. c'est ça qui étonne.",
    phrase: "et il faisait encore jour.",
    taille: "haute",
    ratio: "2/3",
  },
  {
    image: "photos/site/eclipse-4-{w}.webp",
    alt: "un croissant solaire fin et incliné, seul dans le noir",
    titre: "l'éclipse, presque tout",
    categorie: "lumière",
    date: "août 2026",
    lieu: "",
    description: "il ne restait plus qu'un fil. c'est le moment où tout le monde se tait.",
    phrase: "plus personne ne parlait.",
    taille: "haute",
    ratio: "2/3",
  },
  {
    image: "photos/site/eclipse-5-{w}.webp",
    alt: "le dernier croissant de soleil, très mince, avant la fin de l'éclipse",
    titre: "l'éclipse, le dernier fil",
    categorie: "lumière",
    date: "août 2026",
    lieu: "",
    description: "et puis il a recommencé à grandir, comme si de rien n'était.",
    phrase: "il est reparti comme il est venu.",
    taille: "haute",
    ratio: "2/3",
  },
];
