/* ==========================================================================
   virgule. — les photos
   --------------------------------------------------------------------------
   Pour ajouter une photo, ajoute un objet à la liste :

   {
     image: "photos/ma-photo.jpg",   // chemin vers ton fichier (ou URL)
     alt: "description pour les lecteurs d'écran",
     titre: "le titre de la photo",
     categorie: "paysages",          // paysages | macro | animaux | portraits
                                     // architecture | détails | lumière
     date: "mai 2025",
     lieu: "Vercors",
     description: "petit texte affiché en grand format.",
     phrase: "la petite phrase absurde au survol.",
     taille: "grande",               // grande | panorama | haute | moyenne | petite
   }

   ⚠ Les entrées ci-dessous utilisent `picsum:` (images de démonstration).
   Remplace-les par `image:` avec tes propres fichiers, et adapte `alt`.
   Idéalement, respecte à peu près les proportions de chaque taille :
   grande 4:3 · panorama 16:10 · haute 3:4 · moyenne 4:3 · petite 1:1
   ========================================================================== */

const PHOTOS = [
  {
    picsum: 1015,
    alt: "un fjord aux eaux bleues serpente entre de hautes falaises",
    titre: "le fleuve prenait son temps",
    categorie: "paysages",
    date: "mai 2024",
    lieu: "Norvège",
    description: "il pleuvait dix minutes avant. le fleuve a fait comme si de rien n'était.",
    phrase: "celle-là était beaucoup plus belle en vrai.",
    taille: "grande",
  },
  {
    picsum: 1016,
    alt: "des falaises rouges embrasées par la lumière du soir",
    titre: "la falaise ne voulait pas poser",
    categorie: "paysages",
    date: "septembre 2024",
    lieu: "grand ouest",
    description: "le rocher n'a pas bougé depuis. je vérifie régulièrement.",
    phrase: "prise 0,7 seconde avant que tout change.",
    taille: "haute",
  },
  {
    picsum: 237,
    alt: "un chiot noir regarde fixement l'objectif, vu de dessus",
    titre: "le chien qui savait",
    categorie: "animaux",
    date: "mars 2025",
    lieu: "Lyon",
    description: "il a posé exactement quatre secondes. un professionnel.",
    phrase: "il me regarde encore.",
    taille: "petite",
  },
  {
    picsum: 599,
    alt: "une montagne sombre émerge du brouillard au-dessus d'un lac",
    titre: "brouillard, avec insistance",
    categorie: "paysages",
    date: "janvier 2025",
    lieu: "Jura",
    description: "la montagne est là, quelque part. faites-moi confiance.",
    phrase: "le brouillard a signé une décharge.",
    taille: "panorama",
  },
  {
    picsum: 1025,
    alt: "un carlin très digne, enroulé dans une couverture à carreaux",
    titre: "monsieur le directeur",
    categorie: "animaux",
    date: "juin 2024",
    lieu: "Annecy",
    description: "il n'a pas souri. moi non plus. le respect.",
    phrase: "aucune idée de ce que je faisais.",
    taille: "moyenne",
  },
  {
    picsum: 375,
    alt: "une personne en capuche au milieu d'un champ de marguerites, au crépuscule",
    titre: "portrait de quelqu'un de patient",
    categorie: "portraits",
    date: "octobre 2024",
    lieu: "Picardie",
    description: "on a parlé de tout, puis de rien. le déclic est parti entre les deux.",
    phrase: "celle-ci mérite une explication. je n'en ai pas.",
    taille: "haute",
  },
  {
    picsum: 102,
    alt: "des framboises posées sur une table, en très gros plan",
    titre: "framboises, vues de très près",
    categorie: "macro",
    date: "juillet 2025",
    lieu: "le jardin de ma mère",
    description: "ce ne sont pas des champignons. le champignon s'était déjà enfui.",
    phrase: "je jure que le champignon était là.",
    taille: "petite",
  },
  {
    picsum: 164,
    alt: "des maisons anciennes penchées au bord d'un canal",
    titre: "l'immeuble faisait le fier",
    categorie: "architecture",
    date: "novembre 2024",
    lieu: "Bruges",
    description: "quatre siècles qu'ils penchent, et toujours pas un mot d'excuse.",
    phrase: "il penche. c'est lui, pas moi.",
    taille: "grande",
  },
  {
    picsum: 1080,
    alt: "des fraises éclatantes qui remplissent tout le cadre",
    titre: "nature morte, très vivante",
    categorie: "macro",
    date: "février 2026",
    lieu: "ma cuisine",
    description: "la composition a duré moins longtemps que prévu.",
    phrase: "mangées douze minutes après.",
    taille: "moyenne",
  },
  {
    picsum: 1047,
    alt: "une ruelle étroite entre deux hauts immeubles de brique",
    titre: "géométrie sans permis",
    categorie: "architecture",
    date: "août 2024",
    lieu: "Brooklyn",
    description: "quelqu'un a dessiné ça un jour, très sûr de lui. respect.",
    phrase: "l'architecte n'a pas été consulté.",
    taille: "haute",
  },
  {
    picsum: 250,
    alt: "un appareil photo argentique posé sur les touches d'un piano",
    titre: "l'appareil d'un collègue",
    categorie: "détails",
    date: "décembre 2024",
    lieu: "quelque part",
    description: "il attendait quelqu'un. ce n'était pas moi, mais j'ai pris la photo quand même.",
    phrase: "lui aussi, il me jugeait.",
    taille: "petite",
  },
  {
    picsum: 338,
    alt: "une silhouette en capuche marche le long d'une plage grise",
    titre: "inconnu, mais poli",
    categorie: "portraits",
    date: "avril 2025",
    lieu: "Marseille",
    description: "trois mots échangés, une photo, et chacun sa route.",
    phrase: "on ne s'est jamais revus.",
    taille: "moyenne",
  },
  {
    picsum: 206,
    alt: "un verger traversé par une lumière dorée de fin de journée",
    titre: "la lumière de 19h47",
    categorie: "lumière",
    date: "juin 2025",
    lieu: "Drôme",
    description: "à 19h48, plus rien. c'est exactement pour ça que ce métier existe.",
    phrase: "à 19h48, plus rien.",
    taille: "grande",
  },
  {
    picsum: 548,
    alt: "des étincelles s'élèvent d'un feu dans la nuit",
    titre: "poussière en apesanteur",
    categorie: "lumière",
    date: "mars 2026",
    lieu: "l'atelier",
    description: "les étincelles montent, l'appareil suit. c'est le seul plan que j'avais.",
    phrase: "aucun trucage. peu de prudence.",
    taille: "haute",
  },
  {
    picsum: 403,
    alt: "les touches rondes d'une vieille machine à écrire",
    titre: "la machine avait quelque chose à dire",
    categorie: "détails",
    date: "mai 2025",
    lieu: "Turin",
    description: "elle parlait lentement. il fallait rester un peu.",
    phrase: "je n'ai pas osé demander.",
    taille: "moyenne",
  },
];
